name: Build

on:
  workflow_dispatch
  # push:
  #   branches: [ "main" ]

permissions:
  id-token: write
  contents: read
  
jobs:
  app-build:
    runs-on: windows-latest
    name: Application Build

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore XWingTO.sln
    - name: Build
      run: dotnet build XWingTO.sln --no-restore
    - name: Test
      run: dotnet test XWingTO.sln --no-build --verbosity normal
    - name: Install EF tools
      run: dotnet tool install --global dotnet-ef
    - name: Generate migration SQL script
      run: dotnet ef migrations script --idempotent --project ./XWingTO.Web/XWingTO.Web.csproj --output ./XWingTO.sql
    - name: Publish web app
      run: dotnet publish ./XWingTO.Web/XWingTO.Web.csproj -o .\publish\web
    - name: Publish function app
      run: dotnet publish ./XWingTO.Functions/XWingTO.Functions.csproj -o .\publish\functions
    - name: Zip web app
      run: Compress-Archive .\publish\web XWingTO.Web.zip
    - name: Zip function app
      run: Compress-Archive .\publish\functions XWingTO.Functions.zip
    - name: Upload web app artifact
      uses: actions/upload-artifact@v3
      with:
        name: WebApp
        path: .\XWingTO.Web.zip
    - name: Upload function app artifact
      uses: actions/upload-artifact@v3
      with:
        name: FunctionApp
        path: .\XWingTO.Functions.zip
    - name: Upload SQL script
      uses: actions/upload-artifact@v3
      with:
        name: SqlScript
        path: ./XWingTO.sql

  infra-build:
    runs-on: windows-latest
    name: IaC build

    steps:
    - uses: actions/checkout@v3
    - name: Bicep lint 
      run: az bicep build --file ./XWingTO.bicep
    - name: Azure logon
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Bicep Dev validation
      with:
        template: ./XWingTO.bicep
        deploymentMode: Validate
        scope: subscription
        region: uksouth
        parameters: environment=Development sqlAdminPassword=${{ secrets.Validation_SQL_Admin_Password }}
        deploymentName: ${{ github.sha }}
        failOnStdErr: false
    - uses: azure/arm-deploy@v1
      name: Bicep Test validation
      with:
        template: ./XWingTO.bicep
        deploymentMode: Validate
        scope: subscription
        region: uksouth
        parameters: environment=Test sqlAdminPassword=${{ secrets.Validation_SQL_Admin_Password }}
        deploymentName: ${{ github.sha }}
        failOnStdErr: false
    - uses: azure/arm-deploy@v1
      name: Bicep Prod validation
      with:
        template: ./XWingTO.bicep
        deploymentMode: Validate
        scope: subscription
        region: uksouth
        parameters: environment=Production sqlAdminPassword=${{ secrets.Validation_SQL_Admin_Password }}
        deploymentName: ${{ github.sha }}
        failOnStdErr: false
    - run: az logout

  security-scan:
    runs-on: ubuntu-latest
  
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript, csharp
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

#Pull steps up from child workflows
  deploy-dev:
    needs: [app-build, infra-build]
    runs-on: windows-latest
    environment: 
      name: Dev
      url: https://app-xwingto-dev.azurewebsites.net

    steps:
    - name: Azure logon
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: actions/checkout@v3
    - name: Bicep deployment
      id: bicep
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        template: ./XWingTO.bicep
        region: UKSouth
        parameters: environment=Development sqlAdminPassword=${{ secrets.Production_SQL_Admin_Password }}
        failOnStdErr: false
    - name: Download web app artifact
      uses: actions/download-artifact@v3
      with:
        name: WebApp
    - name: Download function app artifact
      uses: actions/download-artifact@v3
      with:
        name: FunctionApp
    - name: Deploy web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.bicep.outputs.appServiceName }}
        package: ./XWingTO.Web.zip
    - name: Deploy function app
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.bicep.outputs.functionAppName }}
        package: ./XWingTO.Functions.zip
    - name: Set DB connection string
      run: az webapp config connection-string set -t SQLAzure -n ${{ steps.bicep.outputs.appServiceName }} --settings XWingTO=${{ steps.bicep.outputs.sqlconnectionString }}
  # DB connstring
# AppInsights key
# Storage queue connstring        
    - name: Download sql script
      uses: actions/download-artifact@v3
      with:
        name: SqlScript
    - name: Azure logon for SQL firewall
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy db
      uses: azure/sql-action@v2.1
      with:
        connection-string: ${{ steps.bicep.outputs.sqlconnectionString }}
        path: ./XWingTO.sql
        action: Script
    - name: Azure logout
      run: az logout

  deploy-test:
    needs: deploy-dev
    runs-on: windows-latest
    environment: 
      name: Test
      url: https://app-xwingto-test.azurewebsites.net

    steps:
    - uses: actions/checkout@v3
    - name: Bicep deployment
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        template: ./XWingTO.bicep
        region: uksouth
        parameters: environment=Test sqlAdminPassword=${{ secrets.Production_SQL_Admin_Password }}
    - name: Download web app artifact
      uses: actions/download-artifact@v3
      with:
        name: WebApp
    - name: Download function app artifact
      uses: actions/download-artifact@v3
      with:
        name: FunctionApp
#    - name: ZAP Scanning
#      uses: zaproxy/action-full-scan@v0.4.0
#      with:
#        target: 'https://www.zaproxy.org/'
    - name: Azure logon
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Azure logout
      run: az logout

  deploy-prod:
    needs: deploy-test
    runs-on: windows-latest
    environment: 
      name: Prod
      url: https://xwing.to

    steps:
    - uses: actions/checkout@v3
    - name: Placeholder
      run: echo "Prod deployment"
    - name: Download web app artifact
      uses: actions/download-artifact@v3
      with:
        name: WebApp
    - name: Download function app artifact
      uses: actions/download-artifact@v3
      with:
        name: FunctionApp
    - name: Azure logon
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#  Availability test
    - name: Azure logout
      run: az logout

#    uses: ./.github/workflows/deployinfrastructure.yml
#    uses: ./.github/workflows/migratedatabase.yml
#    uses: ./.github/workflows/deployapplication.yml
#    uses: ./.github/workflows/deployfunctionapp.yml