name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read
  
jobs:
  app-build:
    runs-on: windows-latest
    name: Application Build

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore XWingTO.sln
    - name: Build
      run: dotnet build XWingTO.sln --no-restore
    - name: Test
      run: dotnet test XWingTO.sln --no-build --verbosity normal
    - name: Install EF tools
      run: dotnet tool install --global dotnet-ef
    - name: Generate migration SQL script
      run: dotnet ef migrations script --idempotent --project ./XWingTO.Web/XWingTO.Web.csproj --output ./XWingTO.sql
    - name: Publish web app
      run: dotnet publish ./XWingTO.Web/XWingTO.Web.csproj -o .\publish\web
    - name: Publish function app
      run: dotnet publish ./XWingTO.Functions/XWingTO.Functions.csproj -o .\publish\functions
    - name: Zip web app
      run: Compress-Archive .\publish\web XWingTO.Web.zip
    - name: Zip function app
      run: Compress-Archive .\publish\functions XWingTO.Functions.zip
    - name: Upload web app artifact
      uses: actions/upload-artifact@v3
      with:
        name: WebApp
        path: .\XWingTO.Web.zip
    - name: Upload function app artifact
      uses: actions/upload-artifact@v3
      with:
        name: FunctionApp
        path: .\XWingTO.Functions.zip
    - name: Upload SQL script
      uses: actions/upload-artifact@v3
      with:
        name: SqlScript
        path: ./XWingTO.sql

  infra-build:
    runs-on: windows-latest
    name: IaC build

    steps:
    - uses: actions/checkout@v3
    - name: Bicep lint 
      run: az bicep build --file ./XWingTO.bicep
    - name: Azure logon
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Bicep Dev validation
      with:
        template: ./XWingTO.bicep
        deploymentMode: Validate
        scope: subscription
        region: uksouth
        parameters: environment=Development sqlAdminPassword=${{ secrets.Validation_SQL_Admin_Password }}
        deploymentName: ${{ github.sha }}
    - uses: azure/arm-deploy@v1
      name: Bicep Test validation
      with:
        template: ./XWingTO.bicep
        deploymentMode: Validate
        scope: subscription
        region: uksouth
        parameters: environment=Test sqlAdminPassword=${{ secrets.Validation_SQL_Admin_Password }}
        deploymentName: ${{ github.sha }}
    - uses: azure/arm-deploy@v1
      name: Bicep Prod validation
      with:
        template: ./XWingTO.bicep
        deploymentMode: Validate
        scope: subscription
        region: uksouth
        parameters: environment=Production sqlAdminPassword=${{ secrets.Validation_SQL_Admin_Password }}
        deploymentName: ${{ github.sha }}

#Pull steps up from child workflows
  deploy-dev:
    needs: [app-build, infra-build]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Placeholder
      run: echo "Dev deployment"

  deploy-test:
    needs: deploy-dev
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Placeholder
      run: echo "Test deployment"

  deploy-prod:
    needs: deploy-test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Placeholder
      run: echo "Prod deployment"

#    uses: ./.github/workflows/deployinfrastructure.yml
#    uses: ./.github/workflows/migratedatabase.yml
#    uses: ./.github/workflows/deployapplication.yml
#    uses: ./.github/workflows/deployfunctionapp.yml
    
  #test: 
    #needs: dev
    #runs-on: windows-latest

    #steps:
  #    - uses: ./.github/workflows/deployinfrastructure.yml
  #    - uses: ./.github/workflows/migratedatabase.yml
  #    - uses: ./.github/workflows/deployapplication.yml
  #    - uses: ./.github/workflows/deployfunctionapp.yml

  #prod:
    #needs: test
    #runs-on: windows-latest

    #steps:
  #    - uses: ./.github/workflows/deployinfrastructure.yml
  #    - uses: ./.github/workflows/migratedatabase.yml
  #    - uses: ./.github/workflows/deployapplication.yml
  #    - uses: ./.github/workflows/deployfunctionapp.yml
