name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore XWingTO.sln
    - name: Build
      run: dotnet build XWingTO.sln --no-restore
    - name: Test
      run: dotnet test XWingTO.sln --no-build --verbosity normal
    - name: Bicep lint 
      run: az bicep build --file ./XWingTO.bicep
    - name: Azure logon
      
    - name: Bicep validate
      uses: azure/arm-deploy@v2

  # dev:
  #   needs: build
  #   runs-on: windows-latest

  #  steps:
  #    - uses: ./.github/workflows/deployinfrastructure.yml
  #    - uses: ./.github/workflows/migratedatabase.yml
  #    - uses: ./.github/workflows/deployapplication.yml
  #    - uses: ./.github/workflows/deployfunctionapp.yml
    
  # test: 
  #   needs: dev
  #   runs-on: windows-latest

  #  steps:
  #    - uses: ./.github/workflows/deployinfrastructure.yml
  #    - uses: ./.github/workflows/migratedatabase.yml
  #    - uses: ./.github/workflows/deployapplication.yml
  #    - uses: ./.github/workflows/deployfunctionapp.yml

  # prod:
  #   needs: test
  #   runs-on: windows-latest

  #  steps:
  #    - uses: ./.github/workflows/deployinfrastructure.yml
  #    - uses: ./.github/workflows/migratedatabase.yml
  #    - uses: ./.github/workflows/deployapplication.yml
  #    - uses: ./.github/workflows/deployfunctionapp.yml
