name: DeployFunctionApp

on:
  workflow_call:

inputs:
  environment:
    required: true

jobs:
  deploy-function-app:
    runs-on: windows-latest
    steps:
    - name: Download function app artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: FunctionApp
    - uses: azure/login@v1
      name: Azure login
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    # - uses: azure/functions-action@v1
    #   with:
    #     app-name: [name]
