name: DeployInfrastructure

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        client-id: [SECRET]
        tenant-id: [SECRET]
        subscription-id: [SECRET]
    - uses: azure/arm-deploy@1
      with:
        deploymentname: ${{ github.sha}}
        template: ./XWingTO.bicep
