name: DeployFunctionApp

on:
  workflow_call:
  
jobs:
  deploy-function-app:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
    - uses: azure/functions-action@v1
      with:
        app-name: [name]
