name: DeployInfrastructure

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

inputs:
  environment:
    required: true

jobs:
  deploy-infrastructure:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Azure login
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@1
      name: Bicep deploy
      with:
        deploymentname: ${{ github.sha }}
        template: ./XWingTO.bicep
        scope: subscription
        region: uksouth
        parameters: environment=${{ env.INPUT_ENVIRONMENT}} sqlAdminPassword=${{ secrets.Production_SQL_Admin_Password }}
