name: DeployApplication

on:
  workflow_call:
  
jobs:
  deploy-application:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
    - uses: azure/webapps-deploy@v2
      with:
        app-name: [name]
