name: DeployApplication

on:
  workflow_call:
  
inputs:
  environment:
    required: true

jobs:
  deploy-application:
    runs-on: windows-latest
    steps:
    - name: Download web app artifact
      uses: actions/download-artifact@v3
      with:
        name: WebApp
    - uses: azure/login@v1
      name: Azure login
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: [name]
