name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore XWingTO.sln
    - name: Build
      run: dotnet build XWingTO.sln --no-restore
    - name: Test
      run: dotnet test XWingTO.sln --no-build --verbosity normal
    - name: Publish data assembly
      run: dotnet publish ./XWingTO.Data/XWingTO.Data.csproj
    - name: Publish web app
      run: dotnet publish ./XWingTO.Web/XWingTO.Web.csproj
    - name: Publish function app
      run: dotnet publish ./XWingTO.Functions/XWingTO.Functions.csproj

  # dev:
  #   needs: build
  #   runs-on: windows-latest

  #   deploy-infrastructure:
  #     uses: ./.github/workflows/deployinfrastructure.yml
  #   migrate-database:
  #     uses: ./.github/workflows/migratedatabase.yml
  #   deploy-application:
  #     uses: ./.github/workflows/deployapplication.yml
  #   deploy-function-app:
  #     uses: ./.github/workflows/deployfunctionapp.yml
    
  # test: 
  #   needs: dev
  #   runs-on: windows-latest

  #   deploy-infrastructure:
  #     uses: ./.github/workflows/deployinfrastructure.yml
  #   migrate-database:
  #     uses: ./.github/workflows/migratedatabase.yml
  #   deploy-application:
  #     uses: ./.github/workflows/deployapplication.yml
  #   deploy-function-app:
  #     uses: ./.github/workflows/deployfunctionapp.yml

  # prod:
  #   needs: test
  #   runs-on: windows-latest

  #   deploy-infrastructure:
  #     uses: ./.github/workflows/deployinfrastructure.yml
  #   migrate-database:
  #     uses: ./.github/workflows/migratedatabase.yml
  #   deploy-application:
  #     uses: ./.github/workflows/deployapplication.yml
  #   deploy-function-app:
  #     uses: ./.github/workflows/deployfunctionapp.yml
