name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore XWingTO.sln
    - name: Build
      run: dotnet build XWingTO.sln --no-restore
    - name: Test
      run: dotnet test XWingTO.sln --no-build --verbosity normal

  # dev:
  #   needs: build
  #   runs-on: windows-latest

  #   steps:
  # Deploy infrastructure
  # Migrate db
  # Deploy web app
  # Deploy function app
    
  # test: 
  #   needs: dev
  #   runs-on: windows-latest

  #   steps:

  # prod:
  #   needs: test
  #   runs-on: windows-latest

  #   steps:
