name: MigrateDatabase

on:
  workflow_call:
  
jobs:
  migrate-database:
    runs-on: windows-latest
    steps:
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        # Specify the script here
        inlineScript: echo Migrating DB