name: MigrateDatabase
# Needs connection string passing in
on:
  workflow_call:
  
jobs:
  migrate-database:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
    - uses: actions/download-artifact@v3
      with:
        name: SqlScript
    - uses: azure/sql-action
      with:
        action: Script
        path: ./XWingTo.sql
#       connectionstring: 
      
